const storageDevices = [
  {
    id: 1,
    name: "Western Digital Blue 1TB HDD",
    image: "",
    capacity: "1TB",
    interface: "SATA 6 Gb/s",
    manufacturer: "Western Digital",
    transferRate: "150 MB/s",
    description:
      "Жорсткий диск Western Digital Blue 1TB призначений для використання в настільних комп'ютерах та ноутбуках",
    formFactor: "3.5 inch",
  },
  {
    id: 2,
    name: "Seagate BarraCuda 2TB HDD",
    image: "",
    capacity: "2TB",
    interface: "SATA 6 Gb/s",
    manufacturer: "Seagate",
    transferRate: "220 MB/s",
    description:
      "Жорсткий диск Seagate BarraCuda 2TB пропонує економічний спосіб зберігання великих обсягів даних з високою продуктивністю",
    formFactor: "3.5 inch",
  },
  {
    id: 3,
    name: "Toshiba X300 4TB HDD",
    image: "",
    capacity: "4TB",
    interface: "SATA 6 Gb/s",
    manufacturer: "Toshiba",
    transferRate: "200 MB/s",
    description:
      "Жорсткий диск Toshiba X300 4TB призначений для геймерів та професійних користувачів, яким потрібна надійність та висока продуктивність",
    formFactor: "3.5 inch",
  },
  {
    id: 4,
    name: "HGST Ultrastar 7K6000 6TB HDD",
    image: "",
    capacity: "6TB",
    interface: "SATA 6 Gb/s",
    manufacturer: "HGST",
    transferRate: "255 MB/s",
    description:
      "Жорсткий диск HGST Ultrastar 7K6000 6TB забезпечує надійне зберігання великих обсягів даних для застосувань, що потребують багато пам'яті",
    formFactor: "3.5 inch",
  },
  {
    id: 5,
    name: "Seagate IronWolf 10TB HDD",
    image: "",
    capacity: "10TB",
    interface: "SATA 6 Gb/s",
    manufacturer: "Seagate",
    transferRate: "210 MB/s",
    description:
      "Жорсткий диск Seagate IronWolf 10TB оптимізований для NAS-систем, забезпечуючи високу надійність та продуктивність",
    formFactor: "3.5 inch",
  },
  {
    id: 6,
    name: "Western Digital Red 3TB HDD",
    image: "",
    capacity: "3TB",
    interface: "SATA 6 Gb/s",
    manufacturer: "Western Digital",
    transferRate: "150 MB/s",
    description:
      "Жорсткий диск Western Digital Red 3TB призначений для NAS-систем та забезпечує надійне та ефективне зберігання даних",
    formFactor: "3.5 inch",
  },
  {
    id: 7,
    name: "Seagate SkyHawk 8TB HDD",
    image: "",
    capacity: "8TB",
    interface: "SATA 6 Gb/s",
    manufacturer: "Seagate",
    transferRate: "210 MB/s",
    description:
      "Жорсткий диск Seagate SkyHawk 8TB оптимізований для систем відеоспостереження DVR та NVR, забезпечуючи надійне зберігання відео",
    formFactor: "3.5 inch",
  },
  {
    id: 8,
    name: "Toshiba N300 6TB HDD",
    image: "",
    capacity: "6TB",
    interface: "SATA 6 Gb/s",
    manufacturer: "Toshiba",
    transferRate: "240 MB/s",
    description:
      "Жорсткий диск Toshiba N300 6TB призначений для NAS-застосувань з високою надійністю та продуктивністю",
    formFactor: "3.5 inch",
  },
  {
    id: 9,
    name: "HGST Deskstar NAS 8TB HDD",
    image: "",
    capacity: "8TB",
    interface: "SATA 6 Gb/s",
    manufacturer: "HGST",
    transferRate: "205 MB/s",
    description:
      "Жорсткий диск HGST Deskstar NAS 8TB забезпечує надійне та великоємне зберігання даних для NAS-середовищ",
    formFactor: "3.5 inch",
  },
  {
    id: 10,
    name: "Western Digital Black 4TB HDD",
    image: "",
    capacity: "4TB",
    interface: "SATA 6 Gb/s",
    manufacturer: "Western Digital",
    transferRate: "180 MB/s",
    description:
      "Жорсткий диск Western Digital Black 4TB призначений для геймерів та креативних професіоналів, яким потрібна висока продуктивність та надійність",
    formFactor: "3.5 inch",
  },
  {
    id: 11,
    name: "Seagate Exos X14 14TB HDD",
    image: "",
    capacity: "14TB",
    interface: "SATA 6 Gb/s",
    manufacturer: "Seagate",
    transferRate: "250 MB/s",
    description:
      "Жорсткий диск Seagate Exos X14 14TB забезпечує величезну ємність та високу продуктивність для центрів обробки даних та корпоративних застосувань",
    formFactor: "3.5 inch",
  },
  {
    id: 12,
    name: "Toshiba P300 2TB HDD",
    image: "",
    capacity: "2TB",
    interface: "SATA 6 Gb/s",
    manufacturer: "Toshiba",
    transferRate: "200 MB/s",
    description:
      "Жорсткий диск Toshiba P300 2TB ідеальний для настільних комп'ютерів, пропонуючи велику ємність та надійну продуктивність",
    formFactor: "3.5 inch",
  },
  {
    id: 13,
    name: "HGST Ultrastar He12 12TB HDD",
    image: "",
    capacity: "12TB",
    interface: "SATA 6 Gb/s",
    manufacturer: "HGST",
    transferRate: "255 MB/s",
    description:
      "Жорсткий диск HGST Ultrastar He12 12TB забезпечує великоємне та надійне зберігання даних для корпоративних та центрів обробки даних",
    formFactor: "3.5 inch",
  },
  {
    id: 14,
    name: "Western Digital Purple 10TB HDD",
    image: "",
    capacity: "10TB",
    interface: "SATA 6 Gb/s",
    manufacturer: "Western Digital",
    transferRate: "175 MB/s",
    description:
      "Жорсткий диск Western Digital Purple 10TB оптимізований для систем відеоспостереження, забезпечуючи надійне зберігання відео високої чіткості",
    formFactor: "3.5 inch",
  },
  {
    id: 15,
    name: "Seagate IronWolf Pro 16TB HDD",
    image: "",
    capacity: "16TB",
    interface: "SATA 6 Gb/s",
    manufacturer: "Seagate",
    transferRate: "250 MB/s",
    description:
      "Жорсткий диск Seagate IronWolf Pro 16TB призначений для NAS-систем, пропонуючи величезну ємність та високу надійність",
    formFactor: "3.5 inch",
  },
  {
    id: 16,
    name: "Samsung 970 EVO Plus 1TB SSD",
    image: "",
    capacity: "1TB",
    interface: "NVMe M.2",
    manufacturer: "Samsung",
    transferRate: "3500 MB/s (read), 3300 MB/s (write)",
    description:
      "Твердотільний накопичувач Samsung 970 EVO Plus 1TB пропонує виключну швидкість та надійність для геймінгу та високопродуктивних обчислень",
    formFactor: "M.2 2280",
  },
  {
    id: 17,
    name: "Western Digital Blue 500GB SSD",
    image: "",
    capacity: "500GB",
    interface: "SATA III",
    manufacturer: "Western Digital",
    transferRate: "560 MB/s (read), 530 MB/s (write)",
    description:
      "Твердотільний накопичувач Western Digital Blue 500GB - надійне та швидке рішення для щоденних обчислень",
    formFactor: "2.5 inch",
  },
  {
    id: 18,
    name: "Crucial MX500 1TB SSD",
    image: "",
    capacity: "1TB",
    interface: "SATA III",
    manufacturer: "Crucial",
    transferRate: "560 MB/s (read), 510 MB/s (write)",
    description:
      "Твердотільний накопичувач Crucial MX500 1TB забезпечує відмінне поєднання швидкості, надійності та ціни для звичайних користувачів",
    formFactor: "2.5 inch",
  },
  {
    id: 19,
    name: "Kingston A2000 1TB SSD",
    image: "",
    capacity: "1TB",
    interface: "NVMe M.2",
    manufacturer: "Kingston",
    transferRate: "2200 MB/s (read), 2000 MB/s (write)",
    description:
      "Твердотільний накопичувач Kingston A2000 1TB пропонує відмінну продуктивність та вартість для високопродуктивних обчислень",
    formFactor: "M.2 2280",
  },
  {
    id: 20,
    name: "Samsung 860 EVO 2TB SSD",
    image: "",
    capacity: "2TB",
    interface: "SATA III",
    manufacturer: "Samsung",
    transferRate: "550 MB/s (read), 520 MB/s (write)",
    description:
      "Твердотільний накопичувач Samsung 860 EVO 2TB - надійне та висококапацитетне рішення для різних обчислювальних потреб",
    formFactor: "2.5 inch",
  },
  {
    id: 21,
    name: "ADATA XPG SX8200 Pro 1TB SSD",
    image: "",
    capacity: "1TB",
    interface: "NVMe M.2",
    manufacturer: "ADATA",
    transferRate: "3500 MB/s (read), 3000 MB/s (write)",
    description:
      "Твердотільний накопичувач ADATA XPG SX8200 Pro 1TB забезпечує топову продуктивність для геймерів та ентузіастів",
    formFactor: "M.2 2280",
  },
  {
    id: 22,
    name: "SanDisk Ultra 3D 1TB SSD",
    image: "",
    capacity: "1TB",
    interface: "SATA III",
    manufacturer: "SanDisk",
    transferRate: "560 MB/s (read), 530 MB/s (write)",
    description:
      "Твердотільний накопичувач SanDisk Ultra 3D 1TB забезпечує високу швидкість та надійність для покращених обчислювальних досвідів",
    formFactor: "2.5 inch",
  },
  {
    id: 23,
    name: "Corsair MP600 2TB SSD",
    image: "",
    capacity: "2TB",
    interface: "NVMe PCIe Gen4",
    manufacturer: "Corsair",
    transferRate: "4950 MB/s (read), 4250 MB/s (write)",
    description:
      "Твердотільний накопичувач Corsair MP600 2TB забезпечує екстремальну продуктивність для найвимогливіших застосувань",
    formFactor: "M.2 2280",
  },
  {
    id: 24,
    name: "Intel 660p Series 2TB SSD",
    image: "",
    capacity: "2TB",
    interface: "NVMe M.2",
    manufacturer: "Intel",
    transferRate: "1800 MB/s (read), 1800 MB/s (write)",
    description:
      "Твердотільний накопичувач Intel 660p Series 2TB забезпечує баланс продуктивності та вартості для звичайних користувачів",
    formFactor: "M.2 2280",
  },
  {
    id: 25,
    name: "Toshiba OCZ RD400 512GB SSD",
    image: "",
    capacity: "512GB",
    interface: "NVMe M.2",
    manufacturer: "Toshiba",
    transferRate: "2600 MB/s (read), 1600 MB/s (write)",
    description:
      "Твердотільний накопичувач Toshiba OCZ RD400 512GB забезпечує високошвидкісне зберігання для геймінгу та професійних застосувань",
    formFactor: "M.2 2280",
  },
  {
    id: 26,
    name: "Samsung 980 PRO 1TB SSD",
    image: "",
    capacity: "1TB",
    interface: "NVMe PCIe Gen4",
    manufacturer: "Samsung",
    transferRate: "7000 MB/s (read), 5000 MB/s (write)",
    description:
      "Твердотільний накопичувач Samsung 980 PRO 1TB забезпечує найвищу продуктивність для геймінгу та професійних робочих навантажень",
    formFactor: "M.2 2280",
  },
  {
    id: 27,
    name: "WD Black SN750 1TB SSD",
    image: "",
    capacity: "1TB",
    interface: "NVMe M.2",
    manufacturer: "Western Digital",
    transferRate: "3470 MB/s (read), 3000 MB/s (write)",
    description:
      "Твердотільний накопичувач WD Black SN750 1TB призначений для геймерів та ентузіастів ПК, яким потрібна топова продуктивність",
    formFactor: "M.2 2280",
  },
  {
    id: 28,
    name: "Kingston KC2500 1TB SSD",
    image: "",
    capacity: "1TB",
    interface: "NVMe M.2",
    manufacturer: "Kingston",
    transferRate: "3500 MB/s (read), 2900 MB/s (write)",
    description:
      "Твердотільний накопичувач Kingston KC2500 1TB пропонує високу продуктивність та надійність для апгрейдів десктопів та ноутбуків",
    formFactor: "M.2 2280",
  },
  {
    id: 29,
    name: "Crucial P5 2TB SSD",
    image: "",
    capacity: "2TB",
    interface: "NVMe M.2",
    manufacturer: "Crucial",
    transferRate: "3400 MB/s (read), 3000 MB/s (write)",
    description:
      "Твердотільний накопичувач Crucial P5 2TB забезпечує високошвидкісну продуктивність та витривалість для інтенсивних робочих навантажень",
    formFactor: "M.2 2280",
  },
  {
    id: 30,
    name: "Sabrent Rocket 4 Plus 2TB SSD",
    image: "",
    capacity: "2TB",
    interface: "NVMe PCIe Gen4",
    manufacturer: "Sabrent",
    transferRate: "7100 MB/s (read), 6600 MB/s (write)",
    description:
      "Твердотільний накопичувач Sabrent Rocket 4 Plus 2TB забезпечує екстремальну продуктивність для геймерів та професіоналів",
    formFactor: "M.2 2280",
  },
  {
    id: 31,
    name: "SanDisk Ultra Flair 128GB USB",
    image: "",
    capacity: "128GB",
    interface: "USB 3.0",
    manufacturer: "SanDisk",
    transferRate: "150 MB/s",
    description:
      "USB-накопичувач SanDisk Ultra Flair 128GB забезпечує високу швидкість USB 3.0 у стильному та міцному металевому корпусі",
    formFactor: "USB Flash Drive",
  },
  {
    id: 32,
    name: "Kingston DataTraveler 100 G3 64GB USB",
    image: "",
    capacity: "64GB",
    interface: "USB 3.0",
    manufacturer: "Kingston",
    transferRate: "100 MB/s",
    description:
      "USB-накопичувач Kingston DataTraveler 100 G3 64GB забезпечує надійне зберігання та швидкісну передачу даних",
    formFactor: "USB Flash Drive",
  },
  {
    id: 33,
    name: "Samsung BAR Plus 256GB USB",
    image: "",
    capacity: "256GB",
    interface: "USB 3.1",
    manufacturer: "Samsung",
    transferRate: "300 MB/s",
    description:
      "USB-накопичувач Samsung BAR Plus 256GB поєднує швидкість і стиль з міцним металевим корпусом та високою продуктивністю",
    formFactor: "USB Flash Drive",
  },
];

function addImage() {
  storageDevices.forEach((storageDevice) => {
    const name = storageDevice.name;
    if (name.includes("HDD")) storageDevice.image = "../img/hdd.jpg";
    else if (name.includes("USB")) storageDevice.image = "../img/usb.jpg";
    else if (name.includes("SSD") && storageDevice.interface.includes("NVMe"))
      storageDevice.image = "../img/ssdnvme.jpg";
    else storageDevice.image = "../img/ssd.jpg";
  });
}
